---
- name: "mkdir caffe src dir"
  file:
    path: "{{ src_dir }}"
    state: "directory"

- name: "clone caffe repo"
  git:
    repo: "{{ repo_url }}"
    dest: "{{ src_dir }}"
    version: "{{ version }}"
    force: "yes"

- name: "generate Makefile.config"
  template:
    src: "Makefile.config.j2"
    dest: "{{ src_dir }}/Makefile.config"

# https://gist.github.com/wangruohui/679b05fcd1466bb0937f#fix-hdf5-naming-problem
- name: "upload Makefile"
  copy:
    src: "Makefile"
    dest: "{{ src_dir }}"

- name: "make"
  shell: "make -j {{ ansible_processor_vcpus * 2}}"
  args:
    chdir: "{{ src_dir }}"

- name: "make"
  shell: "make pycaffe -j {{ ansible_processor_vcpus * 2 }}"
  args:
    chdir: "{{ src_dir }}"

