---
- name: "mkdir caffe src dir"
  file:
    path: "{{ src_dir }}"
    state: "directory"

- name: "clone caffe repo"
  git:
    repo: "{{ repo_url }}"
    dest: "{{ src_dir }}"
    version: "{{ version }}"

- name: "generate Makefile.config"
  template:
    src: "Makefile.config"
    dest: "{{ src_dir }}"

# https://gist.github.com/wangruohui/679b05fcd1466bb0937f#fix-hdf5-naming-problem
- name: "upload Makefile"
  copy:
    src: "Makefile"
    dest: "{{ src_dir }}"

- name: "make"
  make:
    chdir: "{{ src_dir }}/build"
    target: "all"
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus }}"

