---
- block: # install depencencies

  - name: "install dependencies"
    apt:
      name: "{{ item }}"
      state: "present"
      update_cache: "yes"
    with_items: "{{ dependencies }}"

  - name: "install ATLAS"
    apt:
      name: "libatlas-dev"
      state: "present"
    when: blas == "ATLAS"

  - name: "install OpenBLAS"
    apt:
      name: "libopenblas-dev"
      state: "present"
    when: blas == "OpenBLAS"

  become: true

